### ISSUE TITLE
Mosaic Record

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris-data-concierge#10]
Creation of a stand alone "Mosaic" category within a collection's information page.  That way we can log, update and link to georeferenced photo mosaics we have created in the Q drive, without having to note it in the "remarks" or photo index sections...could be useful

**Comment by jwhaney** [comment]
resolved by @adambreznicky via commit 3e9ddfdb221fed67efd0c75e1fda59a51650422c. will see on front end admin console on next redeploy (momentarily).
