### ISSUE TITLE
Problem creating multiple TXDOT photo index entries

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris-data-concierge#14]
Hey y'all,

The interns have been trying to update the concierge with TXDOT indices.  With regards to txdot collections, there are unique mission numbers that can be associated with multiple counties.  If the interns try to add an additional photo index card for a collection that already has an existing photo index card, the database throws an error and they cannot proceed.  (see below)

![git_issue](https://user-images.githubusercontent.com/31768897/46379507-93975d80-c664-11e8-8cfc-e6b398034027.PNG)

**Comment by jwhaney** [comment]
resolved via conversation - RDC will adjust workflow.
